### ISSUE TITLE
Java 18 is not compatible with Android projects

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#1318]
* Exception is:
org.gradle.cache.CacheOpenException: Could not open settings generic class cache for settings file '/Users/runner/work/BabylonReactNative/BabylonReactNative/Apps/Playground/0.71/android/settings.gradle'

A web search relates this issue to Java 18. A check on VMs shows the error appeared over night with a Java update (from 17 to 18)

**Comment by CedricGuillemet** [comment]
For Github action, add this :
```
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
```
