### ISSUE TITLE
Implement validation test infrastructure

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#220]
- [x] Be able to see the tests passing and what tests are currently passing
- [ ] CI to run tests for as many as platforms as possible

**Comment by CedricGuillemet** [comment]
I did some tests with the Linux port and it went pretty well.
It's possible to create a window and render using opengl thanks to the on-demand offscreen window manager. To start it in the CI:
```
  - script: |
      export DISPLAY=:99
      Xvfb :99 -screen 0 1600x900x24 &
      sleep 3
```
Then run the executable.
Publishing the result is easy as well. 
```
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'Rendered Pictures'
      pathtoPublish: 'pathToGeneratedImages'
    displayName: 'Publish Tests Results'
```
the CI pathtoPublish supports files and directories. 
![image](https://user-images.githubusercontent.com/1312968/79445565-2ac0cd80-7fdd-11ea-9e42-758bde435cf9.png)

It will zip the content and list it the artefact list that you can download.
![image](https://user-images.githubusercontent.com/1312968/79445722-68bdf180-7fdd-11ea-91fb-467bdc210ddf.png)
ValidationTests App can save generated images and error images in a particular. We can publish both.

For the Direct3D WARP, it needs some changes in bgfx for creating a special device and related swapchain. I think we need to try that on a smaller sampler (just create the device/swapchain, ensure everything properly initialized) to run on the CI. I don't know if it works without a window. And the CI doesn't provide a WindowManager. So ensuring it works before starting a PR on bgfx is a good thing.

For Metal, I'm still investigating...
